services:
  - type: web
    name: nwac-cache
    env: python
    runtime: python-3.11.9
    buildCommand: bash build.sh
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/project/src/browsers
